// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: sysmon.proto

package sysmon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EveryM   int32 `protobuf:"varint,1,opt,name=every_m,json=everyM,proto3" json:"every_m,omitempty"`
	AverageN int32 `protobuf:"varint,2,opt,name=average_n,json=averageN,proto3" json:"average_n,omitempty"`
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysmon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_sysmon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_sysmon_proto_rawDescGZIP(), []int{0}
}

func (x *Param) GetEveryM() int32 {
	if x != nil {
		return x.EveryM
	}
	return 0
}

func (x *Param) GetAverageN() int32 {
	if x != nil {
		return x.AverageN
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Data_Element `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysmon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_sysmon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_sysmon_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetData() []*Data_Element {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data_Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   []string                    `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	Elements []*Data_Element_ElementData `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *Data_Element) Reset() {
	*x = Data_Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysmon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Element) ProtoMessage() {}

func (x *Data_Element) ProtoReflect() protoreflect.Message {
	mi := &file_sysmon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Element.ProtoReflect.Descriptor instead.
func (*Data_Element) Descriptor() ([]byte, []int) {
	return file_sysmon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Data_Element) GetHeader() []string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Data_Element) GetElements() []*Data_Element_ElementData {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Data_Element_ElementData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []string `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
}

func (x *Data_Element_ElementData) Reset() {
	*x = Data_Element_ElementData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysmon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Element_ElementData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Element_ElementData) ProtoMessage() {}

func (x *Data_Element_ElementData) ProtoReflect() protoreflect.Message {
	mi := &file_sysmon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Element_ElementData.ProtoReflect.Descriptor instead.
func (*Data_Element_ElementData) Descriptor() ([]byte, []int) {
	return file_sysmon_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Data_Element_ElementData) GetElement() []string {
	if x != nil {
		return x.Element
	}
	return nil
}

var File_sysmon_proto protoreflect.FileDescriptor

var file_sysmon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x4e, 0x22, 0xbb, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73,
	0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x88, 0x01, 0x0a, 0x07, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x08,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x27, 0x0a, 0x0b, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x32, 0x3c, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2e, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x53, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0d, 0x2e, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x1a, 0x0c, 0x2e, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x30,
	0x01, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sysmon_proto_rawDescOnce sync.Once
	file_sysmon_proto_rawDescData = file_sysmon_proto_rawDesc
)

func file_sysmon_proto_rawDescGZIP() []byte {
	file_sysmon_proto_rawDescOnce.Do(func() {
		file_sysmon_proto_rawDescData = protoimpl.X.CompressGZIP(file_sysmon_proto_rawDescData)
	})
	return file_sysmon_proto_rawDescData
}

var file_sysmon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sysmon_proto_goTypes = []interface{}{
	(*Param)(nil),                    // 0: sysmon.Param
	(*Data)(nil),                     // 1: sysmon.Data
	(*Data_Element)(nil),             // 2: sysmon.Data.Element
	(*Data_Element_ElementData)(nil), // 3: sysmon.Data.Element.ElementData
}
var file_sysmon_proto_depIdxs = []int32{
	2, // 0: sysmon.Data.data:type_name -> sysmon.Data.Element
	3, // 1: sysmon.Data.Element.elements:type_name -> sysmon.Data.Element.ElementData
	0, // 2: sysmon.SysmonData.getSysmonData:input_type -> sysmon.Param
	1, // 3: sysmon.SysmonData.getSysmonData:output_type -> sysmon.Data
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sysmon_proto_init() }
func file_sysmon_proto_init() {
	if File_sysmon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sysmon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysmon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysmon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysmon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Element_ElementData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sysmon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysmon_proto_goTypes,
		DependencyIndexes: file_sysmon_proto_depIdxs,
		MessageInfos:      file_sysmon_proto_msgTypes,
	}.Build()
	File_sysmon_proto = out.File
	file_sysmon_proto_rawDesc = nil
	file_sysmon_proto_goTypes = nil
	file_sysmon_proto_depIdxs = nil
}
