subsystems:
  la: true
  avgcpu: true
  disksload: true
  disksinfo: true
  networktop: true
  networkstat: true

scrapeinterval: 1s  #default time=5s
cleaninterval: 1m  #default time=5m
depth: 2m  #default 1h

bindings:
  port: 50051 # default = 50051
  address: 0.0.0.0 #default 0.0.0.0

